---

# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Elephant Aviator"
description: "Graphic Design"
email: bchavez.gd@gmail.com

#blog logo
logo: "/assets/images/type-logo-00.png"

# blog cover
cover: "/assets/images/yosemite-falls-pano.jpg"

name: 'Brian Chavez'
author: 'Brian Chavez'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://bchavezgd.github.io" # the base hostname & protocol for your site
baseurl: ""

image-folder: "/assets/article_images"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"

# Filtering Content
show_drafts: true
limit_posts: 10
future: false
unpublished: false

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/bchavez_gd
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="


  - icon:	github
    url:	https://github.com/bchavezgd
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
    
  - icon:	instagram
    url:	https://github.com/abattoirsiren
    desc:	follow
    share_url:
    share_title:
    share_link:

gems: [jekyll-paginate, redcarpet, pygments.rb]
